blackboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/homepage')),
    path('', include('users.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('mainLogin', views.mainLogin, name='mainLogin'),
    path('mainDashboard', views.dashboard, name='mainDashboard'),
    path('approve-user/<int:user_id>/', views.approve_user, name='approve_user'),
    path('disapprove-user/<int:user_id>/', views.disapprove_user, name='disapprove_user'),
    
    path('approve-instructor/<int:instructor_id>/', views.approve_instructor, name='approve_instructor'),
    path('disapprove-instructor/<int:instructor_id>/', views.disapprove_instructor, name='disapprove_instructor'),
    path('<int:user_id>/deleteuser/', views.deleteUser, name='deleteuser'),
    
    path('homepage', views.homepage, name='homepage'),
    path('about', views.about, name='about'),
    path('register', views.register, name='register'),
    path('user_login', views.user_login, name='user_login'),
    path('logout', views.logoutUser, name='logout'),
    
    
    
    path('forum_page', views.forum_page, name='forum_page'),
    path('student_forum', views.student_forum, name='student_forum'),
    path('student_lesson', views.student_lesson, name='student_lesson'),
    path('student_quizzes', views.student_quizzes, name='student_quizzes'),
    path('student_announcement', views.student_announcement, name='student_announcement'),
    path('student_lesson', views.student_lesson, name='student_lesson'),
    path('startquiz/<int:q_id>/', views.student_startQuiz, name='start_quiz'),
     
    path('instructor_lesson', views.instructor_lesson, name='instructor_lesson'),
    path('instructor_quizzes', views.instructor_quizzes, name='instructor_quizzes'),
    path('questions/<int:q_id>/', views.questions, name='questions'),
    path('instructor_forum', views.instructor_forum, name='instructor_forum'),
    path('forum_page1', views.forum_page1, name='forum_page1'),
    path('instructor_lesson', views.instructor_lesson, name='instructor_lesson'),
    path('instructor_announcement', views.instructor_announcements, name='instructor_announcement'),
    
    
    path('<int:announcement_id>/deleteannouncement/', views.deleteAnnouncement, name='deleteannouncement'),
    path('<int:q_id>/deletequestion/', views.deletequestion, name='deletequestion'),
    path('<int:q_id>/deletequiz/', views.deletequiz, name='deletequiz'),
    path('<int:forum_id>/deleteforum/', views.deleteForum, name='deleteforum'),
    path('<int:lesson_id>/deletelesson/', views.deleteLesson, name='deletelesson'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.validators import FileExtensionValidator
# Create your models here.

now = timezone.now()

# Create your models here.

class Quizz(models.Model):
    title = models.TextField()
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name='creator')
    # user_take = models.ForeignKey(User, on_delete=models.CASCADE, related_name='usertaker')
    # deadline = models.DateField()
    # time_limit = models.IntegerField()
    # takers = models.IntegerField(blank=True)
    
class Questions(models.Model):
    name = models.ForeignKey(Quizz, on_delete=models.CASCADE)
    question = models.TextField(blank=True)
    answer = models.TextField()
    
class Lesson(models.Model):
    title = models.TextField()
    description = models.TextField()
    file = models.FileField(upload_to='files', validators=[FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg', 'pdf', 'word', 'ppt', 'excel'])],)
    upload_date = models.DateTimeField(default=now)
    uploader = models.ForeignKey(User, on_delete=models.CASCADE)
    

class Score(models.Model):
    score = models.IntegerField()
    taker = models.ForeignKey(User, on_delete=models.CASCADE)
    quiz = models.ForeignKey(Quizz, on_delete=models.CASCADE)
    
    
    
class Forum(models.Model):
    title = models.CharField(max_length=10000)
    file = models.FileField(
        upload_to='media/announcement',
        validators=[ 
            FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg', 'pdf', 'word', 'ppt', 'xlsx', 'csv', 'gif'])
        ],
        null=True,  # Allow null values
        blank=True  # Also allow empty values (in forms)
    )
    upload_date = models.DateTimeField(default=now)
    description = models.TextField()
    uploader = models.ForeignKey(User, on_delete=models.CASCADE)
    
class Comments(models.Model):
    post = models.ForeignKey(Forum, on_delete=models.CASCADE)
    commentors = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField()
    comment_date = models.DateTimeField(default=now)
    
class Announcement(models.Model):
    title = models.CharField(max_length=10000)
    # file = models.FileField(upload_to='media/event', validators=[FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg', 'pdf', 'word', 'ppt', 'xlsx', 'csv', 'gif'])],)
    upload_date = models.DateTimeField(default=now)
    description = models.TextField()
    uploader = models.ForeignKey(User, on_delete=models.CASCADE)
    like = models.IntegerField()

users/views.py
import random
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.models import User, auth
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from .models import Questions, Quizz, Lesson, Score, Announcement, Forum, Comments
from django.db.models import Count
from datetime import datetime
from django.utils.dateparse import parse_date
# Create your views here.




def mainLogin(request):
    return render(request, 'main/mainLogin.html')

def dashboard(request):
    student = User.objects.filter(last_name='Student').order_by('-id')
    instructor = User.objects.filter(last_name='Teacher').order_by('-id')
    context = {
        'student': student,
        'instructor':instructor
       
    }
    return render(request, 'main/mainDashboard.html', context)


def approve_user(request, user_id):
    user = User.objects.get(pk=user_id)
    user.is_staff = True
    user.save()
    # You can redirect to a success page or to the same page
    return redirect('mainDashboard')

def disapprove_user(request, user_id):
    user = User.objects.get(pk=user_id)
    user.is_staff = False
    user.save()
    # You can redirect to a success page or to the same page
    return redirect('mainDashboard')


def approve_instructor(request, instructor_id):
    user = User.objects.get(pk=instructor_id)
    user.is_superuser = True
    user.save()
    # You can redirect to a success page or to the same page
    return redirect('mainDashboard')

def disapprove_instructor(request, instructor_id):
    user = User.objects.get(pk=instructor_id)
    user.is_superuser = False
    user.save()
    # You can redirect to a success page or to the same page
    return redirect('mainDashboard')


def deleteUser(request, user_id):
    User.objects.filter(id=user_id).delete()
    messages.success(request, 'User Removed')
    return redirect('/mainDashboard')




def about(request):
    return render(request, 'about.html')

def logoutUser(request):
    auth.logout(request)
    messages.success(request, "Logged out Successfully!")
    return redirect('user_login')

def homepage(request):
    return render(request, 'index.html')

def register(request):
    if request.method == 'POST':
        fullname = request.POST['fullname']
        email = request.POST['email']
        role = request.POST['role']
        password = request.POST['password1']
        repeat_password = request.POST['password2']
       
        if password != repeat_password:
            messages.error(request, 'Passwords do not match.')
            return redirect('register')

        if User.objects.filter(email=email).exists():
            messages.error(request, 'This email is already registered.')
            return redirect('register')

        else:
            # Create new user
            user = User.objects.create_user(first_name=fullname, username=email, email=email, password=password, last_name=role)
            user.save()
            messages.success(request, 'You have been registered successfully.')
            return redirect('user_login')

    return render(request, 'register.html')


def user_login(request):
    
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        
        user = authenticate(request, username=email, password=password)
        
        if user is not None:
            login(request, user)
            
            if user.is_superuser:
                return redirect('instructor_lesson') 
            
            elif user.is_staff:
                return redirect('student_lesson')
            
            else:
                messages.error(request, "Wait for Admin to Accept your account")
                return redirect('user_login')
            
        else:
            messages.error(request, "Invalid email or password. Please try again.")
            return redirect('user_login')

    return render(request, 'login.html')



@login_required(login_url='/login')
def student_quizzes(request):
    user = request.user
    quizzes = Quizz.objects.all().order_by('-id')
    taken_quizzes = Score.objects.filter(taker=user).values_list('quiz', flat=True)
    
    context = {
        'quizzes': quizzes,
        'taken_quizzes': taken_quizzes,
    }
    
    return render(request, 'student/quizzes.html', context)


@login_required(login_url='/login')
def student_startQuiz(request, q_id):
    quizz = get_object_or_404(Quizz, id=q_id)
    questions = Questions.objects.filter(name=q_id).order_by('-id')
    
    questions_number = Questions.objects.filter(name=q_id).count()
   
    
    if request.method == 'POST':
        score = request.POST['score']
        
        new_score = Score.objects.create(score=score, quiz=quizz, taker=request.user)

        new_score.save()
        
        messages.success(request, 'You have submitted your score.')
        return redirect('student_quizzes')
        
    context = {
        'quizz': quizz,
        'questions': questions,
        'questions_number':questions_number,
        
    }
    return render(request, 'student/start.html', context)


@login_required(login_url='/login')
def student_announcement(request):
   
    
    announcements = Announcement.objects.all().order_by('-upload_date')
    context = {
        
        'announcements':announcements 
    }
    return render(request, 'student/announcements.html',context)



@login_required(login_url='/login')
def student_lesson(request):

    topic_lists = Lesson.objects.all().order_by('-upload_date')

    context = { 
    
        'topic_lists': topic_lists,
      
    }
    return render(request, 'student/lesson.html', context)


@login_required(login_url='/login')
def student_forum(request):
   
    # Retrieve all forums with comment counts
    forums = Forum.objects.annotate(comment_count=Count('comments')).order_by('-upload_date')
    
    if request.method == 'POST':
        comment = request.POST['comment']
        commentor = request.POST['commentor']
        post_id = request.POST['post']  # Retrieve the post ID
        
        # Get the corresponding Forum instance
        forum = get_object_or_404(Forum, pk=post_id)
        
        new_comment = Comments.objects.create(comment=comment, commentors=request.user, post=forum)
        new_comment.save()
        
    comments_lists = Comments.objects.all().order_by('comment_date')
    
    context = {
        'forums': forums,
        'comments_lists': comments_lists,
    }
    return render(request, 'student/forums.html', context)

def forum_page(request):
   
    # Retrieve all forums with comment counts
    forums = Forum.objects.annotate(comment_count=Count('comments')).order_by('-upload_date')
    
    if request.method == 'POST':
        comment = request.POST['comment']
       
        post_id = request.POST['post']  # Retrieve the post ID
        
        # Get the corresponding Forum instance
        forum = get_object_or_404(Forum, pk=post_id)
        
        new_comment = Comments.objects.create(comment=comment, commentors=request.user, post=forum)
        new_comment.save()
    
    # Get the forum_id from the query parameters
    forum_id = request.GET.get('forum_id')

    # Retrieve the forum object using the forum_id
    forum = Forum.objects.get(id=forum_id)

    # Retrieve all comments related to the forum
    comments = Comments.objects.filter(post=forum)
    
    context = {
        'forum': forum, 
        'comments': comments,
    }
    # Render the forum page template with the forum object and comments
    return render(request, 'student/forumPost.html', context)
























@login_required(login_url='/login')
def instructor_quizzes(request):
    quiz = Quizz.objects.all().order_by('-id')
    
    if request.method == 'POST':
        title = request.POST['title']
        # deadline_str = request.POST['deadline']
        # timelimit = request.POST['timelimit']
        
        
        # deadline_date = datetime.strptime(deadline_str, "%m/%d/%Y").strftime("%Y-%m-%d")
        
        new_quizz = Quizz.objects.create(title=title, creator=request.user)
        new_quizz.save()
        messages.success(request, 'New Quiz Uploaded')
        
    context = {
        'quiz': quiz,
    }
    
    return render(request, 'instructor/quizzes.html', context)


@login_required(login_url='/login')
def questions(request, q_id):
    quizz = get_object_or_404(Quizz, id=q_id)
    questions = Questions.objects.filter(name=q_id).order_by('-id')
    
    if request.method == 'POST':
        question = request.POST['question']

        answer = request.POST['answer']
        
        new_question = Questions.objects.create(name=quizz, question=question, answer=answer)
        new_question.save()
        messages.success(request, 'New Question Uploaded')
        
    context = {
        'quizz': quizz,
        'questions':questions,
    } 
    
    return render(request, 'instructor/questions.html', context)

def deletequestion(request, q_id):
    Questions.objects.filter(id=q_id).delete()
    messages.success(request, 'Question Removed')
    return redirect('/instructor_quizzes')

def deletequiz(request, q_id):
    Quizz.objects.filter(id=q_id).delete()
    messages.success(request, 'Quiz Removed')
    return redirect('/instructor_quizzes')



@login_required(login_url='/login')
def instructor_forum(request):
    authenticated_user = request.user
    students = User.objects.filter(last_name='Student')
    forums = Forum.objects.filter(uploader=authenticated_user).annotate(comment_count=Count('comments')).order_by('-upload_date')
    comments_lists = Comments.objects.all().order_by('comment_date')

    if request.method == 'POST':
        if 'forum_form_submit' in request.POST:
            title = request.POST['title']
            description = request.POST['description']

users/templates/student/announcements.html
{% load static tailwind_tags %}<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta
			name="viewport"
			content="width=device-width, initial-scale=1.0" />
		<title>Announcement</title>
		<link
			rel="stylesheet"
			href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" />
		<link
			href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.css"
			rel="stylesheet" />
		{% tailwind_css %}
	</head>
	{% include 'includes/student_sidebar.html' %}

		<div class="p-4 sm:ml-64 mt-24">
			<div class="mb-8">
				<p class="text-left text-4xl font-bold my-4">Announcements</p>
			</div>


			<div class="p-4">
				<div class="bg-gray-10 items-center justify-start">
					<div class="px-1 sm:px-8 py-1 sm:py-8">
						{% for announcement in announcements %}
						<div class="bg-white rounded-2xl px-10 my-8 py-8 transition border-2 border-black">
							<div class="flex items-center">
								<div class="w-14 h-14 bg-blue-500 rounded-full flex items-center justify-center font-bold text-white">
									<i class="fa fa-user-circle text-xl" aria-hidden="true"></i>
								</div>
								<div class="flex flex-col w-full">
									<div class="flex justify-between">
										<p class="ml-2 text-gray-500">{{announcement.uploader.first_name}}</p>
										
									</div>
									<p class="ml-2 text-xs">Posted an Announcement</p>
								</div>
							</div>
							<div class="mt-4">
								<h1 class="text-lg text-gray-700 font-semibold hover:underline cursor-pointer">
									{{announcement.title}}
								</h1>
								<p class="mt-2 text-sm font-semibold text-gray-400">{{announcement.upload_date}}</p>
								<p class="mt-4 text-md text-gray-600 break-all">{{announcement.description}}</p>
								{% if announcement.file %}
								<img
									src="{{ announcement.file.url }}"
									class="mt-4 rounded-lg"
									alt="" />
								{% endif %}
								<hr />
								<div>
									<img
										src=""
										alt="" />
								</div>
								<div class="flex justify-between items-center">
									<!-- <div class="mt-4 flex items-center space-x-4 py-6">
										<a
											href="#" 
											class="text-md font-semibold hover:text-blue-400 hover:scale-105 duration-300">
											<i class="fa-solid fa-thumbs-up"></i>
											{{ announcement.likes }} Likes
										</a>
									</div> -->
									
								</div>
							</div>
						</div>
						{% endfor %}
					</div>
				</div>
		</div>
<script>
			function searchDivs() {
				var input, filter, titles, i;
				input = document.getElementById("searchInput");
				filter = input.value.toUpperCase();
				titles = document.querySelectorAll(".forumTitle");

				titles.forEach(function (title) {
					var titleText = title.textContent || title.innerText;
					if (titleText.toUpperCase().indexOf(filter) > -1) {
						title.closest(".bg-white").style.display = "";
					} else {
						title.closest(".bg-white").style.display = "none";
					}
				});
			}
		</script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"></script>
	</body>
</html>

users/templates/student/forumPost.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta
			name="viewport"
			content="width=device-width, initial-scale=1.0" />
		<title>Forums</title>
		<link
			rel="stylesheet"
			href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" />
		<link
			href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.css"
			rel="stylesheet" />
		{% tailwind_css %}
	</head>
	<body>
		{% include 'includes/student_sidebar.html' %}

		<div class="p-2 sm:p-4 sm:ml-64 mt-24">
			<div class="">
				<div class="flex items-center justify-start">
					<div class="px-1 sm:px-8 py-1 sm:py-6">
						<div class="bg-white rounded-2xl px-10 py-8 shadow-lg hover:shadow-2xl transition duration-500">
							<div class="flex items-center">
								<div class="w-14 h-14 bg-blue-500 rounded-full flex items-center justify-center font-bold text-white">
									<i class="fa fa-user-circle text-xl" aria-hidden="true"></i>
								</div>
								<p class="ml-2 text-gray-500">{{forum.uploader.first_name}} Posted a forum</p>
							</div>
							<div class="mt-4">
								<h1
									data-modal-target="{{forum.id}}-modal"
									data-modal-toggle="{{forum.id}}-modal"
									class="text-lg text-gray-700 font-semibold hover:underline cursor-pointer">
									{{forum.title}}
								</h1>
								<p class="mt-2 text-sm font-semibold text-gray-400">{{forum.upload_date}}</p>
								<p class="mt-4 text-md text-gray-600 break-all">{{forum.description}}</p>
								{% if forum.file %}
								<img
									src="{{ forum.file.url }}"
									class="mt-4 rounded-lg"
									alt="" />

								{% endif %}
							</div>
						</div>
						<p class="ml-3 py-4 font-bold">Comments</p>
					</div>
				</div>
				<div>
					{% for comment in comments %}
					<div class="flex flex-col py-2 px-8">
						<div class="bg-gray-200 p-2 rounded-xl">
							<div class="flex justify-between items-center mb-2">
								<div class="flex items-center">
									<p class="inline-flex items-center mr-3 text-md text-gray-900 font-bold">
										<!-- <img
											class="mr-2 w-8 h-8 rounded-full"
											src="{{comment.commentors.student.profile_pic}}" /> -->
										{{comment.commentors.first_name}}
									</p>
									<p class="text-sm text-gray-600">{{comment.comment_date}}</p>
								</div>
							</div>
							<p class="text-gray-500 ml-1">{{comment.comment}}</p>
						</div>
					</div>
					{% endfor %}
				</div>

				<form
					class="space-y-4 p-2 bg-white py-2 sticky bottom-0 left-0"
					action="#"
					method="post"
					enctype="multipart/form-data">
					{% csrf_token %}
					<div class="col-span-2">
						<input
							type="text"
							name="post"
							class="bg-gray-50 border hidden border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 w-full p-2.5 placeholder-gray-400"
							value="{{forum.id}}"
							required />

						<input
							type="text"
							name="comment"
							id="title"
							class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 placeholder-gray-400"
							placeholder="Write comment here"
							required />
					</div>
					<div>
						<button
							type="submit"
							class="w-lg text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">
							Comment
						</button>
						<a
							href="{% url 'student_forum' %}"
							class="w-lg text-white bg-red-500 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">
							Back
						</a>
					</div>
				</form>
			</div>
		</div>

		<script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"></script>
	</body>
</html>

users/templates/student/quizzes.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>BSIT Blackboard</title>
		<meta charset="UTF-8" />
		<meta
			name="viewport"
			content="width=device-width, initial-scale=1.0" />
		<meta
			http-equiv="X-UA-Compatible"
			content="ie=edge" />
		<link
			rel="stylesheet"
			href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
		<link
			href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.css"
			rel="stylesheet" />
		{% tailwind_css %}
	</head>

	<body class="bg-gray-200 font-sans leading-normal tracking-normal">
		{% include 'includes/student_sidebar.html' %}

		<div class="p-4 sm:ml-64">
			<div class="flex mx-4 mt-24">
				<p class="text-5xl font-bold mb-24">Quizzes</p>
			</div>

			{% for message in messages%} {% if message.level_tag == 'success' %}
			<p class="text-center text-green-400 font-bold mt-14 text-md">{{message}}</p>
			{% else %}
			<p class="text-center text-red-400 font-bold mt-14 text-md">{{message}}</p>
			{%endif%} {% endfor %}

			<div class="flex justify-evenly flex-wrap">
				{% for quiz in quizzes %}
				<div class="max-w-lg p-6 bg-white border border-gray-200 rounded-lg shadow">
					<div
						id="alert-border-{{ quiz.id }}"
						class="flex items-center p-4 border-t-4 border-orange-300 bg-orange-50"
						role="alert">
						<i
							class="fa fa-exclamation-triangle text-orange-800 animate-bounce"
							aria-hidden="true"></i>
						<div class="ms-3 text-sm font-medium text-orange-800">You can only take this quiz once.</div>
					</div>

					<a href="#">
						<h5 class="mb-2 mt-6 text-2xl font-bold tracking-tight text-gray-900">{{ quiz.title }}</h5>
						<p class="mb-8 text-xs text-gray-400">Created by: {{ quiz.creator.first_name }}</p>
					</a>
					<p class="mb-3 font-normal text-gray-700">Number of Items: {{ quiz.questions_set.all.count }}</p>
					{% with quiz.score_set.all as scores %} {% if scores %}
					<ul class="mb-4">
						{% for score in scores %}
						<li class="font-bold text-blue-400">Your Score: {{ score.score }}</li>
						{% endfor %}
					</ul>
					{% endif %} {% endwith %} {% if quiz.id in taken_quizzes %}
					<a
						href="#"
						class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-red-700 rounded-lg hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300">
						You already taken this quiz
						<svg
							class="rtl:rotate-180 w-3.5 h-3.5 ms-2"
							aria-hidden="true"
							xmlns="http://www.w3.org/2000/svg"
							fill="none"
							viewBox="0 0 14 10">
							<path
								stroke="currentColor"
								stroke-linecap="round"
								stroke-linejoin="round"
								stroke-width="2"
								d="M1 5h12m0 0L9 1m4 4L9 9" />
						</svg>
					</a>

					{% else %}
					<a
						href="{% url 'start_quiz' q_id=quiz.id %}"
						class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300">
						Start Quiz
						<svg
							class="rtl:rotate-180 w-3.5 h-3.5 ms-2"
							aria-hidden="true"
							xmlns="http://www.w3.org/2000/svg"
							fill="none"
							viewBox="0 0 14 10">
							<path
								stroke="currentColor"
								stroke-linecap="round"
								stroke-linejoin="round"
								stroke-width="2"
								d="M1 5h12m0 0L9 1m4 4L9 9" />
						</svg>
					</a>
					{% endif %}
				</div>
				{% endfor %}
			</div>
		</div>

		<script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"></script>
	</body>
</html>